version: "3.5"
services:
  api:
    image: ghcr.io/rudickamladez/cutetix:latest
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    #   args:
    #     USER_ID: 1000
    #     GROUP_ID: 1000
    restart: always
    ports:
      - "8000:80"
    stdin_open: true  # -i
    tty: true         # -t


    
